/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dege.journalnews;

import java.io.File;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author deneg
 */
public class JournalNewsGUI extends javax.swing.JFrame {
   
    private final String defaultSaveFileName = "distributor-state.save";
    private Distributor distributor = new Distributor();
    private final Vector<Subscriber> subscriberListElements = new Vector<>();
    private final Vector<Journal> JournalListElements = new Vector<>();
    private final DefaultListModel subscribersListModel = new DefaultListModel();
    private final DefaultListModel journalsListModel = new DefaultListModel();
    
    
    /**
     * Disables menu LOAD option if the save file does not exist.
     */
    private void checkSaveFile() {
	File saveFile = new File(defaultSaveFileName);
	if (!saveFile.isFile())
	    loadMenuItem.setEnabled(false);
    }
    
    /**
     * Refresh GUI subscribers and journals lists.
     */
    private void refreshGuiLists() {
	// Clear contents.
	subscribersListModel.clear();
	journalsListModel.clear();
	subscriberListElements.clear();
	JournalListElements.clear();

	// Populate lists.
	for (Subscriber aSubscriber : distributor.getSubscribers()) {
	    subscriberListElements.add(aSubscriber);
	    subscribersListModel.addElement(aSubscriber.getName());
	}
	for (Journal aJournal : distributor.getJournals().values()) {
	    JournalListElements.add(aJournal);
	    journalsListModel.addElement(aJournal.getName());
	}	
    }

    /**
     * Creates new form JournalNewsGUI
     */
    public JournalNewsGUI() {
        initComponents();
	initDialogs();
	checkSaveFile();
	
	// New models for GUI lists
	subscribersList.setModel(subscribersListModel);
	journalsList.setModel(journalsListModel);
	
	// Test values for distributor.
//	distributor.addJournal(new Journal("Big Journal", "1266", 4, 80));
//	distributor.addJournal(new Journal("Great Planet", "4354", 2, 50));
//	distributor.addSubscriber(new Individual("Ahmet", "address1"));
//	distributor.addSubscriber(new Corporation("Lone Worker", "address2"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        newJournalDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        newJournalName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newJournalIssn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newJournalFreq = new javax.swing.JTextField();
        newJournalPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        newIndividualDialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newIndividualName = new javax.swing.JTextField();
        newIndividualAddr = new javax.swing.JTextField();
        newIndividualCard = new javax.swing.JTextField();
        newIndividualExpireMonth = new javax.swing.JTextField();
        newIndividualExpireYear = new javax.swing.JTextField();
        newIndividualCVV = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        newCorporationDialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        newCorpName = new javax.swing.JTextField();
        newCorpAddr = new javax.swing.JTextField();
        newCorpBankCode = new javax.swing.JTextField();
        newCorpBankName = new javax.swing.JTextField();
        newCorpIssueDay = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        newCorpAccountNr = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        newCorpIssueMonth = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        newCorpIssueYear = new javax.swing.JTextField();
        newSubscriptionDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        subscribersComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        journalsComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        copiesField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        startMonthField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        startYearField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        subscribersList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        journalsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        loadMenuItem = new javax.swing.JMenuItem();
        addItemMenu = new javax.swing.JMenu();
        newJournalMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        newIndividualMenuItem = new javax.swing.JMenuItem();
        newCorpMenuItem = new javax.swing.JMenuItem();
        newSubscriptionMenuItem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        newJournalDialog.setTitle("New Journal");
        newJournalDialog.setAlwaysOnTop(true);
        newJournalDialog.setSize(new java.awt.Dimension(0, 0));

        jLabel1.setText("Name");

        jLabel3.setText("ISSN");

        jLabel4.setText("Frequency");

        jLabel5.setText("Issue Price");

        jButton1.setText("Ready");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newJournalDialogLayout = new javax.swing.GroupLayout(newJournalDialog.getContentPane());
        newJournalDialog.getContentPane().setLayout(newJournalDialogLayout);
        newJournalDialogLayout.setHorizontalGroup(
            newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJournalDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newJournalDialogLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newJournalFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newJournalDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newJournalName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newJournalDialogLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newJournalIssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newJournalDialogLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newJournalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newJournalDialogLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newJournalDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newJournalFreq, newJournalIssn, newJournalName, newJournalPrice});

        newJournalDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel4, jLabel5});

        newJournalDialogLayout.setVerticalGroup(
            newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJournalDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newJournalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newJournalIssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newJournalFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newJournalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newJournalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newIndividualDialog.setTitle("New Individual");

        jLabel6.setText("Name");

        jLabel7.setText("Address");

        jLabel8.setText("Credit Card");

        jLabel9.setText("Expire Month");

        jLabel10.setText("Expire Year");

        jLabel11.setText("CVV");

        jButton3.setText("Ready");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newIndividualDialogLayout = new javax.swing.GroupLayout(newIndividualDialog.getContentPane());
        newIndividualDialog.getContentPane().setLayout(newIndividualDialogLayout);
        newIndividualDialogLayout.setHorizontalGroup(
            newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newIndividualDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndividualName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndividualAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndividualCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndividualExpireMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndividualExpireYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newIndividualCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newIndividualDialogLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newIndividualDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel6, jLabel7, jLabel8, jLabel9});

        newIndividualDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newIndividualAddr, newIndividualCVV, newIndividualCard, newIndividualExpireMonth, newIndividualExpireYear, newIndividualName});

        newIndividualDialogLayout.setVerticalGroup(
            newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newIndividualDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newIndividualName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newIndividualAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newIndividualCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newIndividualExpireMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newIndividualExpireYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(newIndividualCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newIndividualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newCorporationDialog.setTitle("New Corporation");

        jLabel12.setText("Address");

        jButton5.setText("Ready");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Bank Code");

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setText("Bank Name");

        jLabel15.setText("Day");

        jLabel16.setText("Account Number");

        jLabel17.setText("Name");

        jLabel18.setText("Month");

        jLabel19.setText("Year");

        javax.swing.GroupLayout newCorporationDialogLayout = new javax.swing.GroupLayout(newCorporationDialog.getContentPane());
        newCorporationDialog.getContentPane().setLayout(newCorporationDialogLayout);
        newCorporationDialogLayout.setHorizontalGroup(
            newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCorporationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpIssueDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpIssueYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpIssueMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpAccountNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCorpName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCorporationDialogLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newCorporationDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19});

        newCorporationDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newCorpAccountNr, newCorpAddr, newCorpBankCode, newCorpBankName, newCorpIssueDay, newCorpIssueMonth, newCorpIssueYear, newCorpName});

        newCorporationDialogLayout.setVerticalGroup(
            newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCorporationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(newCorpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(newCorpAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(newCorpBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(newCorpBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(newCorpIssueDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(newCorpIssueMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(newCorpIssueYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(newCorpAccountNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCorporationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        newSubscriptionDialog.setTitle("New Subscription");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Subscribers"));

        subscribersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subscribersComboBox, 0, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subscribersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Journals"));

        journalsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(journalsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(journalsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Number of Copies");

        jLabel21.setText("Start Month");

        jLabel22.setText("Start Year");

        jButton7.setText("Ready");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancel");

        javax.swing.GroupLayout newSubscriptionDialogLayout = new javax.swing.GroupLayout(newSubscriptionDialog.getContentPane());
        newSubscriptionDialog.getContentPane().setLayout(newSubscriptionDialogLayout);
        newSubscriptionDialogLayout.setHorizontalGroup(
            newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copiesField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newSubscriptionDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        newSubscriptionDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel20, jLabel21, jLabel22});

        newSubscriptionDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {copiesField, startMonthField, startYearField});

        newSubscriptionDialogLayout.setVerticalGroup(
            newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSubscriptionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(copiesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(startMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(startYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newSubscriptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JournalNews");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setName(""); // NOI18N

        subscribersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        subscribersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subscribersListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(subscribersList);

        jTabbedPane1.addTab("Subscribers", jScrollPane1);

        journalsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        journalsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                journalsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(journalsList);

        jTabbedPane1.addTab("Journals", jScrollPane2);

        jLabel2.setText("Details");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        detailsTextArea.setEditable(false);
        detailsTextArea.setColumns(15);
        detailsTextArea.setLineWrap(true);
        detailsTextArea.setRows(5);
        jScrollPane3.setViewportView(detailsTextArea);

        fileMenu.setText("File");

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        loadMenuItem.setText("Load");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadMenuItem);

        jMenuBar1.add(fileMenu);

        addItemMenu.setText("Add");

        newJournalMenuItem.setText("New Journal...");
        newJournalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newJournalMenuItemActionPerformed(evt);
            }
        });
        addItemMenu.add(newJournalMenuItem);

        jMenu4.setText("New Subscriber");

        newIndividualMenuItem.setText("New Individual...");
        newIndividualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIndividualMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(newIndividualMenuItem);

        newCorpMenuItem.setText("New Corporation...");
        newCorpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCorpMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(newCorpMenuItem);

        addItemMenu.add(jMenu4);

        newSubscriptionMenuItem.setText("New Subscription...");
        newSubscriptionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubscriptionMenuItemActionPerformed(evt);
            }
        });
        addItemMenu.add(newSubscriptionMenuItem);

        jMenuBar1.add(addItemMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(refreshButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // Refresh lists when button is pressed.
	refreshGuiLists();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void subscribersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subscribersListValueChanged
        // When subscriber list item selected, show details.
	if (subscribersList.getValueIsAdjusting() == false) {
	    
	    if (subscribersList.getSelectedIndex() != -1) {
		// Selected something.
		
		// Clear written text.
		detailsTextArea.setText(null);
		
		// Getting Subscriber object.
		int i = subscribersList.getSelectedIndex();
		Subscriber aSubscriber = subscriberListElements.get(i);
		
		// Writing Subscriber details.
		if (aSubscriber instanceof Individual) {
		    detailsTextArea.append("Type: Individual\n\n");
		} else {
		    detailsTextArea.append("Type: Corporation\n\n");
		}
		detailsTextArea.append(aSubscriber.getName() + "\n");
		detailsTextArea.append(aSubscriber.getAddress() + "\n");
		detailsTextArea.append("\n");
		detailsTextArea.append(aSubscriber.getBillingInformation());
	    }
	}
	
	else {
	    // clear journal list selection.
	    journalsList.clearSelection();    
	}

    }//GEN-LAST:event_subscribersListValueChanged

    private void journalsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_journalsListValueChanged
        // When journal list item selected, show details.
        if (journalsList.getValueIsAdjusting() == false) {

            if (journalsList.getSelectedIndex() != -1) {
                // Selected something.

                // Clear written text.
                detailsTextArea.setText(null);

                // Getting Subscriber object.
                int i = journalsList.getSelectedIndex();
                Journal aJournal = JournalListElements.get(i);

                // Writing Subscriber details.
                detailsTextArea.append("Type: Journal\n\n");
                detailsTextArea.append(aJournal.getName() + "\n");
                detailsTextArea.append(aJournal.getIssn() + "\n");
                detailsTextArea.append(aJournal.getFrequency()+ "\n");
                detailsTextArea.append(Double.toString(aJournal.getIssuePrice()));
            }
        }
	
	else {
	    // Clear subscriber list selection.
	    subscribersList.clearSelection();
	}
    }//GEN-LAST:event_journalsListValueChanged

    private void newJournalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newJournalMenuItemActionPerformed
        // User clicked on 'New Journal...' menu item.
	// Reset dialog fields.
	resetNewJournalDialog();
	newJournalDialog.setVisible(true);
	
    }//GEN-LAST:event_newJournalMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // User clicked 'Ready' at newJournalDialog.
	
	// Get user input.
	// TODO: Prevent wrong character errors.
	String name = newJournalName.getText();
	String issn = newJournalIssn.getText();
	int frequency = Integer.parseInt(newJournalFreq.getText());
	double price = Double.parseDouble(newJournalPrice.getText());
	
	// New Journal instance.
	Journal newJournal = new Journal(name, issn, frequency, price);
	distributor.addJournal(newJournal);
	
	// Hide dialog.
	newJournalDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // User clicked 'Cancel' at newJournalDialog.
	resetNewJournalDialog();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void newIndividualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIndividualMenuItemActionPerformed
        // User clicked on 'New Individual...'.
	// Reset dialog fields.
	resetNewIndividualDialog();
	newIndividualDialog.setVisible(true);
    }//GEN-LAST:event_newIndividualMenuItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // User clicked 'Ready' at newIndividualDialog.
	
	// Get user input.
	String name = newIndividualName.getText();
	String addr = newIndividualAddr.getText();
	String card = newIndividualCard.getText();
	int expireMonth = Integer.parseInt(newIndividualExpireMonth.getText());
	int expireYear = Integer.parseInt(newIndividualExpireYear.getText());
	int cvv = Integer.parseInt(newIndividualCVV.getText());
	
	// New Individual.
	Individual newIndividual = new Individual(name, addr);
	newIndividual.setCreditCardNr(card);
	newIndividual.setExpireDate(expireMonth, expireYear);
	newIndividual.setCVV(cvv);
	distributor.addSubscriber(newIndividual);
	
	// Hide dialog.
	newIndividualDialog.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // User clicked 'Cancel' at newIndividualDialog.
	resetNewIndividualDialog();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // User clicked 'Cancel' at newCorporationDialog.
	resetNewCorporationDialog();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // User clicked 'Ready' at newCorporationDialog.

	// Get user input.
	String name = newCorpName.getText();
	String addr = newCorpAddr.getText();
	String bank = newCorpBankName.getText();
	int code = Integer.parseInt(newCorpBankCode.getText());
	int day = Integer.parseInt(newCorpIssueDay.getText());
	int month = Integer.parseInt(newCorpIssueMonth.getText());
	int year = Integer.parseInt(newCorpIssueYear.getText());
	int account = Integer.parseInt(newCorpAccountNr.getText());
	
	// New Corporation.
	Corporation newCorporation = new Corporation(name, addr);
	newCorporation.setBankName(bank);
	newCorporation.setBankCode(code);
	newCorporation.setIssueDate(day, month, year);
	newCorporation.setAccountNumber(account);
	distributor.addSubscriber(newCorporation);
	
	// Hide dialog.
	newCorporationDialog.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void newCorpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCorpMenuItemActionPerformed
        // User clicked 'New Corporation...'
	// Reset dialog fields.
	resetNewCorporationDialog();
	newCorporationDialog.setVisible(true);
    }//GEN-LAST:event_newCorpMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // User selected 'Save'
	distributor.saveState(defaultSaveFileName);
	loadMenuItem.setEnabled(true);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        // User selected 'Load'
	distributor.readState(defaultSaveFileName);
	refreshGuiLists();
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void newSubscriptionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubscriptionMenuItemActionPerformed
        // User selected new subscription.
	resetNewSubscriptionDialog();
	newSubscriptionDialog.setVisible(true);
    }//GEN-LAST:event_newSubscriptionMenuItemActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // User clicked 'Ready' on newSubscriptionDialog.
	
	// Get user input.
	int copies = Integer.parseInt(copiesField.getText());
	int month = Integer.parseInt(startMonthField.getText());
	int year = Integer.parseInt(startYearField.getText());
	
	// Get Journal and Subscriber selections.
	Journal journal = JournalListElements
		.get(journalsComboBox.getSelectedIndex());
	Subscriber subscriber = subscriberListElements
		.get(subscribersList.getSelectedIndex());
	
	// New subscription.
	Subscription s = new Subscription(new DateInfo(month, year), copies, 
		journal, subscriber);
	distributor.addSubscription(journal.getIssn(), subscriber, s);
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void resetNewJournalDialog() {
	// Reset newJournalDialog instance.
	newJournalDialog.pack();
	newJournalName.setText(null);
	newJournalIssn.setText(null);
	newJournalFreq.setText(null);
	newJournalPrice.setText(null);
    }
    
    private void resetNewIndividualDialog() {
	// Reset newIndividaulDialog instance.
	newIndividualDialog.pack();
	newIndividualName.setText(null);
	newIndividualAddr.setText(null);
	newIndividualCard.setText(null);
	newIndividualExpireMonth.setText(null);
	newIndividualExpireYear.setText(null);
	newIndividualCVV.setText(null);
    }
    
    private void resetNewCorporationDialog() {
	// Reset newCorporationDialog instance.
	newCorporationDialog.pack();
	newCorpName.setText(null);
	newCorpAddr.setText(null);
	newCorpBankCode.setText(null);
	newCorpBankName.setText(null);
	newCorpIssueDay.setText(null);
	newCorpIssueMonth.setText(null);
	newCorpIssueYear.setText(null);
	newCorpAccountNr.setText(null);
    }
    
    private void resetNewSubscriptionDialog() {
	// Reset dialog.
	newSubscriptionDialog.pack();
	copiesField.setText(null);
	startMonthField.setText(null);
	startYearField.setText(null);
	
	// Load items from lists.
	DefaultComboBoxModel model;
	model = new DefaultComboBoxModel<>(subscribersListModel.toArray());
	subscribersComboBox.setModel(model);
	model = new DefaultComboBoxModel<>(journalsListModel.toArray());
	journalsComboBox.setModel(model);
    }
    
    private void initDialogs() {
	// Init dialogs.
	newJournalDialog.pack();
	newIndividualDialog.pack();
	newCorporationDialog.pack();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JournalNewsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addItemMenu;
    private javax.swing.JTextField copiesField;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> journalsComboBox;
    private javax.swing.JList<String> journalsList;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JTextField newCorpAccountNr;
    private javax.swing.JTextField newCorpAddr;
    private javax.swing.JTextField newCorpBankCode;
    private javax.swing.JTextField newCorpBankName;
    private javax.swing.JTextField newCorpIssueDay;
    private javax.swing.JTextField newCorpIssueMonth;
    private javax.swing.JTextField newCorpIssueYear;
    private javax.swing.JMenuItem newCorpMenuItem;
    private javax.swing.JTextField newCorpName;
    private javax.swing.JDialog newCorporationDialog;
    private javax.swing.JTextField newIndividualAddr;
    private javax.swing.JTextField newIndividualCVV;
    private javax.swing.JTextField newIndividualCard;
    private javax.swing.JDialog newIndividualDialog;
    private javax.swing.JTextField newIndividualExpireMonth;
    private javax.swing.JTextField newIndividualExpireYear;
    private javax.swing.JMenuItem newIndividualMenuItem;
    private javax.swing.JTextField newIndividualName;
    private javax.swing.JDialog newJournalDialog;
    private javax.swing.JTextField newJournalFreq;
    private javax.swing.JTextField newJournalIssn;
    private javax.swing.JMenuItem newJournalMenuItem;
    private javax.swing.JTextField newJournalName;
    private javax.swing.JTextField newJournalPrice;
    private javax.swing.JDialog newSubscriptionDialog;
    private javax.swing.JMenuItem newSubscriptionMenuItem;
    private javax.swing.JButton refreshButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField startMonthField;
    private javax.swing.JTextField startYearField;
    private javax.swing.JComboBox<String> subscribersComboBox;
    private javax.swing.JList<String> subscribersList;
    // End of variables declaration//GEN-END:variables
}
