/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dege.journalnews;

import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author deneg
 */
public class JournalNewsGUI extends javax.swing.JFrame {
    
    private Distributor distributor = new Distributor();
    private final Vector<Subscriber> subscriberListElements = new Vector<>();
    private final Vector<Journal> JournalListElements = new Vector<>();
    private final DefaultListModel subscribersListModel = new DefaultListModel();
    private final DefaultListModel journalsListModel = new DefaultListModel();
    
    /**
     * Refresh GUI subscribers and journals lists.
     */
    public void refreshGuiLists() {
	// Clear contents.
	subscribersListModel.clear();
	journalsListModel.clear();
	subscriberListElements.clear();
	JournalListElements.clear();

	// Populate lists.
	for (Subscriber aSubscriber : distributor.getSubscribers()) {
	    subscriberListElements.add(aSubscriber);
	    subscribersListModel.addElement(aSubscriber.getName());
	}
	for (Journal aJournal : distributor.getJournals().values()) {
	    JournalListElements.add(aJournal);
	    journalsListModel.addElement(aJournal.getName());
	}	
    }

    /**
     * Creates new form JournalNewsGUI
     */
    public JournalNewsGUI() {
        initComponents();
	
	// Test values for distributor.
	distributor.addJournal(new Journal("Big Journal", "1266", 4, 80));
	distributor.addJournal(new Journal("Great Planet", "4354", 2, 50));
	distributor.addSubscriber(new Individual("Ahmet", "address1"));
	distributor.addSubscriber(new Corporation("Lone Worker", "address2"));
	
	subscribersList.setModel(subscribersListModel);
	journalsList.setModel(journalsListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        subscribersList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        journalsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JournalNews");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setName(""); // NOI18N

        subscribersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        subscribersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subscribersListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(subscribersList);

        jTabbedPane1.addTab("Subscribers", jScrollPane1);

        journalsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        journalsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                journalsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(journalsList);

        jTabbedPane1.addTab("Journals", jScrollPane2);

        jLabel2.setText("Details");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        detailsTextArea.setEditable(false);
        detailsTextArea.setColumns(15);
        detailsTextArea.setLineWrap(true);
        detailsTextArea.setRows(5);
        jScrollPane3.setViewportView(detailsTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(refreshButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // Refresh lists when button is pressed.
	refreshGuiLists();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void subscribersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subscribersListValueChanged
        // When subscriber list item selected, show details.
	if (subscribersList.getValueIsAdjusting() == false) {
	    
	    if (subscribersList.getSelectedIndex() != -1) {
		// Selected something.
		
		// Clear written text.
		detailsTextArea.setText(null);
		
		// Getting Subscriber object.
		int i = subscribersList.getSelectedIndex();
		Subscriber aSubscriber = subscriberListElements.get(i);
		
		// Writing Subscriber details.
		if (aSubscriber instanceof Individual) {
		    detailsTextArea.append("Type: Individual\n\n");
		} else {
		    detailsTextArea.append("Type: Corporation\n\n");
		}
		detailsTextArea.append(aSubscriber.getName() + "\n");
		detailsTextArea.append(aSubscriber.getAddress() + "\n");
		detailsTextArea.append("\n");
		detailsTextArea.append(aSubscriber.getBillingInformation());
	    }
	}
    }//GEN-LAST:event_subscribersListValueChanged

    private void journalsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_journalsListValueChanged
        // When journal list item selected, show details.
	if (journalsList.getValueIsAdjusting() == false) {
	    
	    if (journalsList.getSelectedIndex() != -1) {
		// Selected something.
		
		// Clear written text.
		detailsTextArea.setText(null);
		
		// Getting Subscriber object.
		int i = journalsList.getSelectedIndex();
		Journal aJournal = JournalListElements.get(i);
		
		// Writing Subscriber details.
		detailsTextArea.append("Type: Journal\n\n");
		detailsTextArea.append(aJournal.getName() + "\n");
		detailsTextArea.append(aJournal.getIssn() + "\n");
		detailsTextArea.append(aJournal.getFrequency()+ "\n");
		detailsTextArea.append(Double.toString(aJournal.getIssuePrice()));
	    }
	}
    }//GEN-LAST:event_journalsListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JournalNewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JournalNewsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> journalsList;
    private javax.swing.JButton refreshButton;
    private javax.swing.JList<String> subscribersList;
    // End of variables declaration//GEN-END:variables
}
